server:
  port: 8088

spring:
  datasource:
    # 新版本必须指定是否使用ssl连接：&useSSL=false
    url: jdbc:mysql://192.168.3.26:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  redis:
    # database设置使用哪个数据库，在redis-cli中使用命令select 1来使用该库
    database: 1
    host: 192.168.3.26
    port: 6379
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # 开启查询SQL日志